import type { BngProject, ProjectPhoto } from "./types";

const photo = (path: string, alt: string, caption: string): ProjectPhoto => ({
  src: `/bng-projects/${path}`,
  alt,
  caption,
});

// DH amounts are confirmed directly, never converted from the older EUR campaigns.
// Commercial handoff and validation notes: docs/DEVELOPER-HANDOFF.md.
export const PROJECTS: BngProject[] = [
  {
    id: "jardin-alma",
    name: "Jardin d’Alma",
    kind: "villa",
    category: "Villas avec piscine privée",
    headline: "Votre villa avec piscine.",
    highlight: "Dès 2,9 millions de DH.",
    description: "Trois chambres, un jardin, votre piscine et un rooftop. Une villa de 179 m² dans une résidence sécurisée, au KM3 de la route d’Ourika.",
    price: 2900000,
    surface: "179 m² habitables",
    format: "3 chambres · jardin privé",
    location: "KM3 · Route d’Ourika",
    airport: "12 min",
    delivery: "1er semestre 2028",
    features: ["Piscine privée", "Rooftop", "Padel & fitness", "Résidence sécurisée"],
    photos: [
      photo("jardin-alma/site/jardin-alma-01-villa-1.jpg", "Projection 3D d’une villa Jardin d’Alma avec sa piscine et son jardin privés", "Votre piscine, votre jardin"),
      photo("jardin-alma/site/jardin-alma-02-villa-2.jpg", "Seconde perspective 3D d’une villa du programme Jardin d’Alma", "Une architecture contemporaine"),
      photo("jardin-alma/site/jardin-alma-03-rendu-1.jpg", "Projection 3D du séjour Jardin d’Alma ouvert sur le jardin", "Le séjour ouvert sur le jardin"),
      photo("jardin-alma/site/jardin-alma-04-rendu-2.jpg", "Projection 3D de la cuisine ouverte et de l’escalier d’une villa Jardin d’Alma", "La cuisine ouverte"),
      photo("jardin-alma/site/jardin-alma-05-rendu-3.jpg", "Projection 3D de la salle à manger Jardin d’Alma", "L’espace à partager"),
      photo("jardin-alma/site/jardin-alma-06-rendu-4.jpg", "Projection 3D du salon et de ses grandes baies dans une villa Jardin d’Alma", "La lumière au quotidien"),
    ],
    payments: [
      { percent: 30, label: "À la réservation", shortLabel: "Réservation", event: "reservation", month: 0 },
      { percent: 20, label: "À 6 mois", shortLabel: "6 mois", event: "scheduled", month: 6 },
      { percent: 20, label: "À 12 mois", shortLabel: "12 mois", event: "scheduled", month: 12 },
      { percent: 20, label: "À 18 mois", shortLabel: "18 mois", event: "scheduled", month: 18 },
      { percent: 10, label: "À la remise des clés", shortLabel: "Clés", event: "keys" },
    ],
    source: "https://bngimmo.com/projets/jardin-alma",
    tour: "https://vertex-france.com/PACKAGE/BNG_IMMO/ALMA/navigation/menu/index.html#gallery",
  },
  {
    id: "m-resort",
    name: "M Resort",
    kind: "apartment",
    category: "Appartements · esprit resort",
    headline: "Marrakech, côté lagon.",
    highlight: "Dès 1 252 000 DH.",
    description: "Du studio à l’appartement deux chambres, avec terrasse ou jardin selon le lot. Deux piscines, du padel et des commerces au KM3 de la route d’Amizmiz.",
    price: 1252000,
    surface: "Surfaces selon le lot",
    format: "Studios · 2 chambres",
    location: "KM3 · Route d’Amizmiz",
    airport: "10 min",
    delivery: "Octobre 2028",
    features: ["2 piscines, dont un lagon", "2 terrains de padel", "Salle de sport", "Parking en sous-sol"],
    photos: [
      photo("m-resort/site/m-resort-01-vue-aerienne.jpg", "Projection 3D des bassins et des palmiers au cœur de M Resort", "Le lagon au cœur du resort"),
      photo("m-resort/site/m-resort-02-piscine-lagon.jpg", "Projection 3D de la piscine et des transats de M Resort", "Les journées au bord de l’eau"),
      photo("m-resort/site/m-resort-06-terrasse.jpg", "Projection 3D d’une terrasse M Resort donnant sur la piscine", "Une terrasse sur le lagon"),
      photo("m-resort/legacy/03-interieur-1.jpg", "Projection 3D d’un séjour M Resort avec cuisine ouverte", "Des intérieurs chaleureux"),
      photo("m-resort/legacy/04-interieur-2.jpg", "Projection 3D d’une chambre avec bureau et lits superposés à M Resort", "Une chambre pour la famille"),
      photo("m-resort/site/m-resort-03-vue-exterieure.jpg", "Projection 3D des façades végétalisées de M Resort", "L’architecture du resort"),
    ],
    payments: [
      { percent: 30, label: "À la réservation", shortLabel: "Réservation", event: "reservation", month: 0 },
      { percent: 15, label: "À 6 mois", shortLabel: "6 mois", event: "scheduled", month: 6 },
      { percent: 15, label: "À 12 mois", shortLabel: "12 mois", event: "scheduled", month: 12 },
      { percent: 40, label: "À la remise des clés", shortLabel: "Clés", event: "keys" },
    ],
    source: "https://bngimmo.com/projets/m-resort",
    tour: "https://vertex-france.com/PACKAGE/GHAITI/M_RESORT/navigation/menu/index.html#model",
  },
  {
    id: "naia-hills",
    name: "Naïa Hills",
    kind: "land",
    category: "Terrains pour villas",
    headline: "Le terrain de vos envies.",
    highlight: "Dès 1,5 million de DH.",
    description: "Votre terrain dès 500 m² sur la route d’Amizmiz. Un programme de 79 parcelles avec espaces verts, padel et fitness extérieur pour imaginer votre future villa.",
    price: 1500000,
    pricePerM2: 3000,
    surface: "Dès 500 m² de terrain",
    format: "Terrain pour villa · R+1",
    location: "Route d’Amizmiz",
    airport: "15 min",
    delivery: "Décembre 2027",
    features: ["Terrain dès 500 m²", "Padel", "Fitness extérieur", "Aire de jeux"],
    photos: [
      photo("naia-hills/site/naia-hills-01-entrance.jpg", "Projection 3D de l’entrée paysagée de Naïa Hills", "L’entrée de Naïa Hills"),
      photo("naia-hills/site/naia-hills-02-padel-court.jpg", "Projection 3D du terrain de padel de Naïa Hills", "Le padel entre voisins"),
      photo("naia-hills/site/naia-hills-03-fitness-area.jpg", "Projection 3D de l’espace fitness extérieur de Naïa Hills", "Le sport en plein air"),
      photo("naia-hills/site/naia-hills-06-aerien-2.jpg", "Projection 3D des espaces de jeux et de sport de Naïa Hills", "Des espaces pour toute la famille"),
      photo("naia-hills/site/naia-hills-04-plan-masse.jpg", "Plan de masse illustré des parcelles du programme Naïa Hills", "Le plan du programme"),
    ],
    payments: [
      { percent: 30, label: "À la réservation", shortLabel: "Réservation", event: "reservation", month: 0 },
      { percent: 40, label: "À 6 mois", shortLabel: "6 mois", event: "scheduled", month: 6 },
      { percent: 15, label: "À 12 mois", shortLabel: "12 mois", event: "scheduled", month: 12 },
      { percent: 15, label: "À la remise du titre", shortLabel: "Remise du titre", event: "title_notary" },
    ],
    source: "https://bngimmo.com/projets/naia-hills",
    tour: "https://vertex-france.com/PACKAGE/BNG_IMMO/NAIA_HILLS/navigation/menu/index.html#model",
  },
  {
    id: "elyazia",
    name: "Elyazia",
    kind: "apartment",
    category: "Studios, appartements & duplex",
    headline: "Votre adresse à Marrakech.",
    highlight: "Dès 869 500 DH.",
    description: "Du studio au duplex, une résidence sur la route de Casablanca. Piscine, fitness sur le toit et parking sécurisé accompagnent votre quotidien.",
    price: 869500,
    surface: "Surfaces selon le lot",
    format: "Studios · 2 chambres · duplex",
    location: "Route de Casablanca",
    proximity: { label: "Guéliz", duration: "5 min" },
    delivery: "2027",
    features: ["Piscine", "Fitness sur le toit", "Parking sécurisé", "Terrasses selon le lot"],
    photos: [
      photo("elyazia/site/elyazia-05-rendu.jpg", "Projection 3D de la piscine et des terrasses sur le toit d’Elyazia", "Marrakech depuis le rooftop"),
      photo("elyazia/site/elyazia-01-facade-large.jpg", "Projection 3D de la façade principale de la résidence Elyazia", "Votre nouvelle adresse"),
      photo("elyazia/site/elyazia-03-salon.jpg", "Projection 3D du salon à double hauteur d’un duplex Elyazia", "Le volume d’un duplex"),
      photo("elyazia/site/elyazia-04-salle-de-bain.jpg", "Projection 3D d’une salle de bain de la résidence Elyazia", "Des lignes épurées"),
      photo("elyazia/site/elyazia-02-facade-perspective.jpg", "Projection 3D en perspective des façades et balcons d’Elyazia", "L’architecture de la résidence"),
    ],
    payments: [
      { percent: 40, label: "À la réservation", shortLabel: "Réservation", event: "reservation", month: 0 },
      { percent: 25, label: "À 6 mois", shortLabel: "6 mois", event: "scheduled", month: 6 },
      { percent: 20, label: "À 12 mois", shortLabel: "12 mois", event: "scheduled", month: 12 },
      { percent: 15, label: "À la remise des clés", shortLabel: "Clés", event: "keys" },
    ],
    source: "https://bngimmo.com/projets/elyazia",
    tour: "https://www.vertex-france.com/PACKAGE/BNG_IMMO/HALIMA_SAADIA/navigation/menu/index.html#model",
  },
  {
    id: "ayline-garden",
    name: "Ayline Garden",
    kind: "land",
    category: "Terrains pour villas",
    headline: "Dessinez votre future villa.",
    highlight: "Dès 1,75 million de DH.",
    description: "Un terrain dès 500 m² pour construire votre villa à quatre façades. Entre les routes d’Ourika et de Tahanaout, derrière Jardin d’Alma.",
    price: 1750000,
    pricePerM2: 3500,
    surface: "Dès 500 m² de terrain",
    format: "Terrain pour villa · 4 façades",
    location: "Entre Ourika et Tahanaout",
    airport: "15 min",
    delivery: "Décembre 2026",
    features: ["Terrain dès 500 m²", "4 façades", "Construction R+1", "Sous-sol possible"],
    photos: [
      photo("ayline-garden/site/ayline-garden-02-plan.jpg", "Projection aérienne du programme de terrains Ayline Garden avec villas illustratives", "Le programme, en perspective"),
      photo("ayline-garden/site/ayline-garden-01-villa.jpg", "Villa illustrative présentée pour le programme de terrains Ayline Garden, construction non comprise", "Inspiration villa · terrain vendu seul"),
    ],
    payments: [
      { percent: 80, label: "À la réservation", shortLabel: "Réservation", event: "reservation", month: 0 },
      { percent: 20, label: "À la remise du titre", shortLabel: "Remise du titre", event: "title_notary" },
    ],
    source: "https://bngimmo.com/projets/ayline-garden",
    tour: "https://www.vertex-france.com/PACKAGE/BNG_IMMO/AYLINE_1/navigation/menu/index.html#model",
  },
];
